const INIT_APP = 'INIT_APP'

const INCREMENT = 'INCREMENT'
const DECREMENT = 'DECREMENT'

const CHANGE_THEME = 'CHANGE_THEME'

const ENABLE_BUTTONS = 'ENABLE_BUTTONS'
const DISABLE_BUTTONS = 'DISABLE_BUTTONS'

export {INIT_APP, INCREMENT, DECREMENT, CHANGE_THEME, ENABLE_BUTTONS, DISABLE_BUTTONS}